
services:
  admin-app:
    build:
      context: ./../../apps/frontend/admin/admin-app
      dockerfile: Dockerfile
    ports:
      - "7001:3000"
    environment:
      - NODE_ENV=production

  blog-app:
    build:
      context: ./../../apps/frontend/consumer/blog-app
      dockerfile: Dockerfile
    ports:
      - "7002:3000"
    environment:
      - NODE_ENV=production


  edtech-app:
    build:
      context: ./../../apps/frontend/consumer/edtech-app
      dockerfile: Dockerfile
    ports:
      - "7003:3000"
    environment:
      - NODE_ENV=production


  nocode-app:
    build:
      context: ./../../apps/frontend/consumer/nocode-app
      dockerfile: Dockerfile
    ports:
      - "7004:3000"
    environment:
      - NODE_ENV=production

  restaurant-app:
    build:
      context: ./../../apps/frontend/consumer/restaurant-app
      dockerfile: Dockerfile
    ports:
      - "7005:3000"
    environment:
      - NODE_ENV=production

  
  admin-service:
    build:
      context: ./../../apps/backend/admin/admin-service
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=production
      
  common-service:
    build:
      context: ./../../apps/backend/consumer/common-service
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production

  blog-service:
    build:
      context: ./../../apps/backend/consumer/blog-service
      dockerfile: Dockerfile
    ports:
      - "8003:3000"
    environment:
      - NODE_ENV=production

  edtech-service:
    build:
      context: ./../../apps/backend/consumer/edtech-service
      dockerfile: Dockerfile
    ports:
      - "8004:3000"
    environment:
      - NODE_ENV=production

  nocode-service:
    build:
      context: ./../../apps/backend/consumer/nocode-service
      dockerfile: Dockerfile
    ports:
      - "8005:3000"
    environment:
      - NODE_ENV=production
      
  restaurant-service:
    build:
      context: ./../../apps/backend/consumer/restaurant-service
      dockerfile: Dockerfile
    ports:
      - "8006:3000"
    environment:
      - NODE_ENV=production

